setwd('C:\\Users\\USER\\Desktop\\IT24103847')
student_data <- read.csv("Exercise.csv", header = TRUE)
summary(student_data$X1)
hist(student_data$X1, main = "Histogram of Age X1", xlab = "Age", ylab = "Frequency")
student_data$X2 <- factor(student_data$X2, levels = c(1, 2), labels = c("Male", "Female"))
Gender_freq <- table(student_data$X2)
student_data$X3 <- factor(student_data$X3, levels = c(1, 2, 3), labels = c("Type 1", "Type 2", "Type 3"))
barplot(Gender_freq, main = "Bar Chart of Gender X2", xlab = "Gender", ylab = "Count")
boxplot(X1 ~ X3, data = student_data, main = "Age by Accommodation Type", xlab = "Accommodation Type", ylab = "Age")
